name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker-compose -f docker-compose.yml up --build -d

      - name: Run tests (если есть)
        run: |
          docker-compose exec -T php php /var/www/html/path_to_test_script.php

      - name: Clean up
        run: |
          docker-compose down

